name: ai_aliya_frontend
description: Flutter UI for an open-source AI voice assistant
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.13.0
  permission_handler: ^11.3.1
  record: ^5.1.2
  path_provider: ^2.1.3
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
